apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: k8s-client
spec:
  serviceName: "k8s-client"
  selector:
    matchLabels:
      app: k8s-client
  replicas: 5 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: k8s-client
    spec:
      volumes:
        - name: shared-train-data # 학습데이터 저장용
          emptyDir: {}
        - name: shared-model # 모델 저장용
          emptyDir: {}
      containers:
          - name: client
            image: docker.io/tpah30/fl_client:1.0
            resources:
              requests:
                memory: "2Gi"
                cpu: "1000m"
                # nvidia.com/gpu: "1"
              # limits:
              #   memory: "4Gi"
              #   cpu: "2500m"
            ports:
              - containerPort: 8002
            env:
            - name: REPO_URL
              value: "https://github.com/gachon-CCLab/FedOps.git"
            - name: GIT_DIR
              value: "FedOps/k8s_simulation/client"
            - name: GIT_TAG
              value: "main"
            - name: GRPC_POLL_STRATEGY
              value: "epoll1"
            - name: MY_POD_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            volumeMounts:
            - name: shared-train-data
              mountPath: /traindata #read
            - name: shared-model
              mountPath: /model #read/write

          - name: client-manager
            image: docker.io/tpah30/git_clone:1.0
            resources:
              limits:
                memory: "2Gi"
                cpu: "1000m"
            ports:
              - containerPort: 8003
            env:
            - name: REPO_URL
              value: "https://github.com/gachon-CCLab/FedOps.git"
            - name: GIT_DIR
              value: "FedOps/k8s_simulation/client_manager"
            - name: GIT_TAG
              value: "main"
            volumeMounts:
              - name: shared-model
                mountPath: /model #write
