// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transport.proto

package flwr.android_client;

public interface ClientMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:flwr.proto.ClientMessage)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.flwr.proto.ClientMessage.DisconnectRes disconnect_res = 1;</code>
   * @return Whether the disconnectRes field is set.
   */
  boolean hasDisconnectRes();
  /**
   * <code>.flwr.proto.ClientMessage.DisconnectRes disconnect_res = 1;</code>
   * @return The disconnectRes.
   */
  flwr.android_client.ClientMessage.DisconnectRes getDisconnectRes();

  /**
   * <code>.flwr.proto.ClientMessage.GetPropertiesRes get_properties_res = 2;</code>
   * @return Whether the getPropertiesRes field is set.
   */
  boolean hasGetPropertiesRes();
  /**
   * <code>.flwr.proto.ClientMessage.GetPropertiesRes get_properties_res = 2;</code>
   * @return The getPropertiesRes.
   */
  flwr.android_client.ClientMessage.GetPropertiesRes getGetPropertiesRes();

  /**
   * <code>.flwr.proto.ClientMessage.GetParametersRes get_parameters_res = 3;</code>
   * @return Whether the getParametersRes field is set.
   */
  boolean hasGetParametersRes();
  /**
   * <code>.flwr.proto.ClientMessage.GetParametersRes get_parameters_res = 3;</code>
   * @return The getParametersRes.
   */
  flwr.android_client.ClientMessage.GetParametersRes getGetParametersRes();

  /**
   * <code>.flwr.proto.ClientMessage.FitRes fit_res = 4;</code>
   * @return Whether the fitRes field is set.
   */
  boolean hasFitRes();
  /**
   * <code>.flwr.proto.ClientMessage.FitRes fit_res = 4;</code>
   * @return The fitRes.
   */
  flwr.android_client.ClientMessage.FitRes getFitRes();

  /**
   * <code>.flwr.proto.ClientMessage.EvaluateRes evaluate_res = 5;</code>
   * @return Whether the evaluateRes field is set.
   */
  boolean hasEvaluateRes();
  /**
   * <code>.flwr.proto.ClientMessage.EvaluateRes evaluate_res = 5;</code>
   * @return The evaluateRes.
   */
  flwr.android_client.ClientMessage.EvaluateRes getEvaluateRes();

  public flwr.android_client.ClientMessage.MsgCase getMsgCase();
}
