// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transport.proto

package flwr.android_client;

public interface ParametersOrBuilder extends
    // @@protoc_insertion_point(interface_extends:flwr.proto.Parameters)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated bytes tensors = 1;</code>
   * @return A list containing the tensors.
   */
  java.util.List<com.google.protobuf.ByteString> getTensorsList();
  /**
   * <code>repeated bytes tensors = 1;</code>
   * @return The count of tensors.
   */
  int getTensorsCount();
  /**
   * <code>repeated bytes tensors = 1;</code>
   * @param index The index of the element to return.
   * @return The tensors at the given index.
   */
  com.google.protobuf.ByteString getTensors(int index);

  /**
   * <code>string tensor_type = 2;</code>
   * @return The tensorType.
   */
  java.lang.String getTensorType();
  /**
   * <code>string tensor_type = 2;</code>
   * @return The bytes for tensorType.
   */
  com.google.protobuf.ByteString
      getTensorTypeBytes();
}
