// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transport.proto

package flwr.android_client;

/**
 * Protobuf type {@code flwr.proto.Parameters}
 */
public  final class Parameters extends
    com.google.protobuf.GeneratedMessageLite<
        Parameters, Parameters.Builder> implements
    // @@protoc_insertion_point(message_implements:flwr.proto.Parameters)
    ParametersOrBuilder {
  private Parameters() {
    tensors_ = emptyProtobufList();
    tensorType_ = "";
  }
  public static final int TENSORS_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.ByteString> tensors_;
  /**
   * <code>repeated bytes tensors = 1;</code>
   * @return A list containing the tensors.
   */
  @java.lang.Override
  public java.util.List<com.google.protobuf.ByteString>
      getTensorsList() {
    return tensors_;
  }
  /**
   * <code>repeated bytes tensors = 1;</code>
   * @return The count of tensors.
   */
  @java.lang.Override
  public int getTensorsCount() {
    return tensors_.size();
  }
  /**
   * <code>repeated bytes tensors = 1;</code>
   * @param index The index of the element to return.
   * @return The tensors at the given index.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getTensors(int index) {
    return tensors_.get(index);
  }
  private void ensureTensorsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<com.google.protobuf.ByteString> tmp = tensors_;
    if (!tmp.isModifiable()) {
      tensors_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }
  /**
   * <code>repeated bytes tensors = 1;</code>
   * @param index The index to set the value at.
   * @param value The tensors to set.
   */
  private void setTensors(
      int index, com.google.protobuf.ByteString value) {
    java.lang.Class<?> valueClass = value.getClass();
  ensureTensorsIsMutable();
    tensors_.set(index, value);
  }
  /**
   * <code>repeated bytes tensors = 1;</code>
   * @param value The tensors to add.
   */
  private void addTensors(com.google.protobuf.ByteString value) {
    java.lang.Class<?> valueClass = value.getClass();
  ensureTensorsIsMutable();
    tensors_.add(value);
  }
  /**
   * <code>repeated bytes tensors = 1;</code>
   * @param values The tensors to add.
   */
  private void addAllTensors(
      java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
    ensureTensorsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, tensors_);
  }
  /**
   * <code>repeated bytes tensors = 1;</code>
   */
  private void clearTensors() {
    tensors_ = emptyProtobufList();
  }

  public static final int TENSOR_TYPE_FIELD_NUMBER = 2;
  private java.lang.String tensorType_;
  /**
   * <code>string tensor_type = 2;</code>
   * @return The tensorType.
   */
  @java.lang.Override
  public java.lang.String getTensorType() {
    return tensorType_;
  }
  /**
   * <code>string tensor_type = 2;</code>
   * @return The bytes for tensorType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTensorTypeBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(tensorType_);
  }
  /**
   * <code>string tensor_type = 2;</code>
   * @param value The tensorType to set.
   */
  private void setTensorType(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    tensorType_ = value;
  }
  /**
   * <code>string tensor_type = 2;</code>
   */
  private void clearTensorType() {

    tensorType_ = getDefaultInstance().getTensorType();
  }
  /**
   * <code>string tensor_type = 2;</code>
   * @param value The bytes for tensorType to set.
   */
  private void setTensorTypeBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    tensorType_ = value.toStringUtf8();

  }

  public static flwr.android_client.Parameters parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static flwr.android_client.Parameters parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static flwr.android_client.Parameters parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static flwr.android_client.Parameters parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static flwr.android_client.Parameters parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static flwr.android_client.Parameters parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static flwr.android_client.Parameters parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static flwr.android_client.Parameters parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static flwr.android_client.Parameters parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static flwr.android_client.Parameters parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static flwr.android_client.Parameters parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static flwr.android_client.Parameters parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(flwr.android_client.Parameters prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code flwr.proto.Parameters}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        flwr.android_client.Parameters, Builder> implements
      // @@protoc_insertion_point(builder_implements:flwr.proto.Parameters)
      flwr.android_client.ParametersOrBuilder {
    // Construct using flwr.android_client.Parameters.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>repeated bytes tensors = 1;</code>
     * @return A list containing the tensors.
     */
    @java.lang.Override
    public java.util.List<com.google.protobuf.ByteString>
        getTensorsList() {
      return java.util.Collections.unmodifiableList(
          instance.getTensorsList());
    }
    /**
     * <code>repeated bytes tensors = 1;</code>
     * @return The count of tensors.
     */
    @java.lang.Override
    public int getTensorsCount() {
      return instance.getTensorsCount();
    }
    /**
     * <code>repeated bytes tensors = 1;</code>
     * @param index The index of the element to return.
     * @return The tensors at the given index.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getTensors(int index) {
      return instance.getTensors(index);
    }
    /**
     * <code>repeated bytes tensors = 1;</code>
     * @param value The tensors to set.
     * @return This builder for chaining.
     */
    public Builder setTensors(
        int index, com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTensors(index, value);
      return this;
    }
    /**
     * <code>repeated bytes tensors = 1;</code>
     * @param value The tensors to add.
     * @return This builder for chaining.
     */
    public Builder addTensors(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.addTensors(value);
      return this;
    }
    /**
     * <code>repeated bytes tensors = 1;</code>
     * @param values The tensors to add.
     * @return This builder for chaining.
     */
    public Builder addAllTensors(
        java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
      copyOnWrite();
      instance.addAllTensors(values);
      return this;
    }
    /**
     * <code>repeated bytes tensors = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTensors() {
      copyOnWrite();
      instance.clearTensors();
      return this;
    }

    /**
     * <code>string tensor_type = 2;</code>
     * @return The tensorType.
     */
    @java.lang.Override
    public java.lang.String getTensorType() {
      return instance.getTensorType();
    }
    /**
     * <code>string tensor_type = 2;</code>
     * @return The bytes for tensorType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTensorTypeBytes() {
      return instance.getTensorTypeBytes();
    }
    /**
     * <code>string tensor_type = 2;</code>
     * @param value The tensorType to set.
     * @return This builder for chaining.
     */
    public Builder setTensorType(
        java.lang.String value) {
      copyOnWrite();
      instance.setTensorType(value);
      return this;
    }
    /**
     * <code>string tensor_type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTensorType() {
      copyOnWrite();
      instance.clearTensorType();
      return this;
    }
    /**
     * <code>string tensor_type = 2;</code>
     * @param value The bytes for tensorType to set.
     * @return This builder for chaining.
     */
    public Builder setTensorTypeBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTensorTypeBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:flwr.proto.Parameters)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new flwr.android_client.Parameters();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "tensors_",
            "tensorType_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0001\u0000\u0001\u001c\u0002\u0208" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<flwr.android_client.Parameters> parser = PARSER;
        if (parser == null) {
          synchronized (flwr.android_client.Parameters.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<flwr.android_client.Parameters>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:flwr.proto.Parameters)
  private static final flwr.android_client.Parameters DEFAULT_INSTANCE;
  static {
    Parameters defaultInstance = new Parameters();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Parameters.class, defaultInstance);
  }

  public static flwr.android_client.Parameters getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Parameters> PARSER;

  public static com.google.protobuf.Parser<Parameters> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

