// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transport.proto

package flwr.android_client;

public interface ScalarOrBuilder extends
    // @@protoc_insertion_point(interface_extends:flwr.proto.Scalar)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>double double = 1;</code>
   * @return Whether the double field is set.
   */
  boolean hasDouble();
  /**
   * <code>double double = 1;</code>
   * @return The double.
   */
  double getDouble();

  /**
   * <pre>
   * float float = 2;
   * int32 int32 = 3;
   * int64 int64 = 4;
   * uint32 uint32 = 5;
   * uint64 uint64 = 6;
   * sint32 sint32 = 7;
   * </pre>
   *
   * <code>sint64 sint64 = 8;</code>
   * @return Whether the sint64 field is set.
   */
  boolean hasSint64();
  /**
   * <pre>
   * float float = 2;
   * int32 int32 = 3;
   * int64 int64 = 4;
   * uint32 uint32 = 5;
   * uint64 uint64 = 6;
   * sint32 sint32 = 7;
   * </pre>
   *
   * <code>sint64 sint64 = 8;</code>
   * @return The sint64.
   */
  long getSint64();

  /**
   * <pre>
   * fixed32 fixed32 = 9;
   * fixed64 fixed64 = 10;
   * sfixed32 sfixed32 = 11;
   * sfixed64 sfixed64 = 12;
   * </pre>
   *
   * <code>bool bool = 13;</code>
   * @return Whether the bool field is set.
   */
  boolean hasBool();
  /**
   * <pre>
   * fixed32 fixed32 = 9;
   * fixed64 fixed64 = 10;
   * sfixed32 sfixed32 = 11;
   * sfixed64 sfixed64 = 12;
   * </pre>
   *
   * <code>bool bool = 13;</code>
   * @return The bool.
   */
  boolean getBool();

  /**
   * <code>string string = 14;</code>
   * @return Whether the string field is set.
   */
  boolean hasString();
  /**
   * <code>string string = 14;</code>
   * @return The string.
   */
  java.lang.String getString();
  /**
   * <code>string string = 14;</code>
   * @return The bytes for string.
   */
  com.google.protobuf.ByteString
      getStringBytes();

  /**
   * <code>bytes bytes = 15;</code>
   * @return Whether the bytes field is set.
   */
  boolean hasBytes();
  /**
   * <code>bytes bytes = 15;</code>
   * @return The bytes.
   */
  com.google.protobuf.ByteString getBytes();

  public flwr.android_client.Scalar.ScalarCase getScalarCase();
}
