// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transport.proto

package flwr.android_client;

public interface ServerMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:flwr.proto.ServerMessage)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.flwr.proto.ServerMessage.ReconnectIns reconnect_ins = 1;</code>
   * @return Whether the reconnectIns field is set.
   */
  boolean hasReconnectIns();
  /**
   * <code>.flwr.proto.ServerMessage.ReconnectIns reconnect_ins = 1;</code>
   * @return The reconnectIns.
   */
  flwr.android_client.ServerMessage.ReconnectIns getReconnectIns();

  /**
   * <code>.flwr.proto.ServerMessage.GetPropertiesIns get_properties_ins = 2;</code>
   * @return Whether the getPropertiesIns field is set.
   */
  boolean hasGetPropertiesIns();
  /**
   * <code>.flwr.proto.ServerMessage.GetPropertiesIns get_properties_ins = 2;</code>
   * @return The getPropertiesIns.
   */
  flwr.android_client.ServerMessage.GetPropertiesIns getGetPropertiesIns();

  /**
   * <code>.flwr.proto.ServerMessage.GetParametersIns get_parameters_ins = 3;</code>
   * @return Whether the getParametersIns field is set.
   */
  boolean hasGetParametersIns();
  /**
   * <code>.flwr.proto.ServerMessage.GetParametersIns get_parameters_ins = 3;</code>
   * @return The getParametersIns.
   */
  flwr.android_client.ServerMessage.GetParametersIns getGetParametersIns();

  /**
   * <code>.flwr.proto.ServerMessage.FitIns fit_ins = 4;</code>
   * @return Whether the fitIns field is set.
   */
  boolean hasFitIns();
  /**
   * <code>.flwr.proto.ServerMessage.FitIns fit_ins = 4;</code>
   * @return The fitIns.
   */
  flwr.android_client.ServerMessage.FitIns getFitIns();

  /**
   * <code>.flwr.proto.ServerMessage.EvaluateIns evaluate_ins = 5;</code>
   * @return Whether the evaluateIns field is set.
   */
  boolean hasEvaluateIns();
  /**
   * <code>.flwr.proto.ServerMessage.EvaluateIns evaluate_ins = 5;</code>
   * @return The evaluateIns.
   */
  flwr.android_client.ServerMessage.EvaluateIns getEvaluateIns();

  public flwr.android_client.ServerMessage.MsgCase getMsgCase();
}
