apiVersion: apps/v1
kind: Deployment
metadata:
  name: fl-server-st
spec:
  replicas: 1
  selector:
    matchLabels:
      run: fl-server-st
  template:
    metadata:
      labels:
        run: fl-server-st
    spec:
      containers:
        - name: server-manager
          image: docker.io/tpah30/git_clone:1.1
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
          ports:
            - containerPort: 8000
          env:
          - name: REPO_URL
            value: "https://github.com/gachon-CCLab/FedOps.git"
          - name: GIT_DIR
            value: "FedOps/server_manager"
          - name: GIT_TAG
            value: "main"
          imagePullPolicy: Always
