apiVersion: apps/v1
kind: Deployment
metadata:
  name: fl-server-st-test
spec:
  replicas: 1
  selector:
    matchLabels:
      run: fl-server-st-test
  template:
    metadata:
      labels:
        run: fl-server-st-test
    spec:
      containers:
        - name: server-manager
          image: docker.io/hoo0681/gitclone_python:0.1
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
          ports:
            - containerPort: 8000
          env:
          - name: REPO_URL
            value: "https://github.com/gachon-CCLab/FedOps.git"
          - name: GIT_DIR
            value: "server_manager"
          - name: GIT_TAG
            value: "main"
