client:
  task:
    name: "646f419d9412e787a370d614"
  data:
    name: 'SaMD'
    validation_split: 0.2
    label_count: 5
  wandb:
    api_key: "eb56a89a7457704c55789c584a3546c707d737f8"
    account: "yangsemo"

server:
  fl_round:
    num_rounds: 20 # FL round
    local_epochs: 5 # Client training epochs
    batch_size: 128
    val_steps: 32

  aggregation:
    fedAvg:
      fraction_fit: 1.0  # Percentage of client learning engagement
      fraction_evaluate: 1.0  # Percentage of client assessment participation
      min_fit_clients: 5  # Minimum number of training clients
      min_evaluate_clients: 5  # Minimum number of evaluation clients
      min_available_clients: 5 # Minimum number of clients
