client:
  task:
    name: "64f99bb134a89971e54d09d9"
  data:
    name: 'cifar10'
    validation_split: 0.2
    label_count: 10
  wandb:
    api_key: "001470b62268462c3c179bb6ac7ce0dfc64b657b"
    account: "gyom1204"

server:
  fl_round:
    num_rounds: 5 # FL round
    local_epochs: 5 # Client training epochs
    batch_size: 128
    val_steps: 32

  aggregation:
    fedAvg:
      fraction_fit: 1.0  # Percentage of client learning engagement
      fraction_evaluate: 1.0  # Percentage of client assessment participation
      min_fit_clients: 5  # Minimum number of training clients
      min_evaluate_clients: 5  # Minimum number of evaluation clients
      min_available_clients: 5 # Minimum number of clients
