# Common
random_seed: 42
lr: 0.0001

model_type: 'Pytorch'
model:
  _target_: models.HatefulMemesFusionModel
  text_hidden_dim: 768
  image_output_dim: 128
  fusion_output_dim: 256
  output_size: 2  # ✅ add this line

dataset:
  name: 'hateful_memes'
  validation_split: 0.2

# Client
task_id: 'hatetaskthree'

wandb: 
  use: false
  key: 'your-wandb-key'
  account: 'your-wandb-account'
  project: '${dataset.name}_${task_id}'

# FL setup
num_epochs: 1
batch_size: 32
num_rounds: 2
clients_per_round: 2

server:
  strategy:
    _target_: flwr.server.strategy.FedAvg
    fraction_fit: 0.00001
    fraction_evaluate: 0.000001
    min_fit_clients: ${clients_per_round}
    min_available_clients: ${clients_per_round}
    min_evaluate_clients: ${clients_per_round}
