apiVersion: apps/v1
kind: Deployment
metadata:
  name: fl-perf
  namespace: fedops
spec:
  replicas: 1
  selector:
    matchLabels:
      run: fl-perf
  template:
    metadata:
      labels:
        run: fl-perf
    spec:
      serviceAccountName: fedops-sa
      containers:
        - name: fl-perf
          image: docker.io/tpah30/git_clone:1.1
          resources:
            limits:
              memory: "2Gi"
              cpu: "1000m"
          ports:
            - containerPort: 8000
          env:
          - name: REPO_URL
            value: "https://github.com/gachon-CCLab/FedOps.git"
          - name: GIT_DIR
            value: "FedOps/fl_performance"
          - name: GIT_TAG
            value: "main"
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: mongodb-uri
                key: MONGODB_URI
          - name: MONGODB_DATABASE
            valueFrom:
              secretKeyRef:
                name: mongodb-uri
                key: MONGODB_DATABASE
          imagePullPolicy: Always
