# Common
random_seed: 42

learning_rate: 0.00005   # local lr for optimizer (fallback when not using layer-wise)
model_type: 'Pytorch'    # keep as-is

model:
  _target_: models.HatefulMemesFusionModel
  output_size: 2
  text_hidden_dim: 768
  image_output_dim: 256
  fusion_output_dim: 256
  freeze_bert: false
  pretrained_vision: true

dataset:
  name: 'HatefulMemes'
  validation_split: 0.2

# FedOps task (web/backend)
task_id: 'fedmaptasks'   # Task Name registered in FedOps Website

wandb:
  use: false
  key: 'your wandb api key'
  account: 'your wandb account'
  project: '${dataset.name}_${task_id}'

# Training
num_epochs: 1
batch_size: 32
num_rounds: 20
clients_per_round: 2
client_idx: 0

# Flower server binding (FedOps server wraps this)
server_address: '0.0.0.0:8094'

# Strategy (use FedMAP custom strategy via Hydra)
server:
  strategy:
    _target_: fedmap.strategy.ModalityAwareAggregation
    aggregator_path: "aggregator_mlp.pth"
    input_dim: 10
    hidden_dim: 16
    aggregator_lr: 0.001
    entropy_coeff: 0.01
    n_trials_per_round: 6
    perf_mix_lambda: 0.7
    z_clip: 3.0

# Server-side evaluation data (Google Drive zip)
server_data:
  gdrive_zip_url: "https://drive.google.com/uc?id=1PEjxFajumhAopGlLxpirXmH5jJ_FQ3AW"
  local_zip: "server_data.zip"
  dir: "server_data"
